F Legg til en docker compose i meta for å kjøre opp postgresbase for …
navikt/tiltakspenger pull request #1
Opened 2023-12-08 12:03 UTC by richardmartinsen

…vedtak og meldekort

2023-12-08 14:28 UTC, benedihm requested changes

2023-12-08 14:28 UTC, benedihm commented on docker-compose.yml
> +      context: ./tiltakspenger-vedtak
Jeg fikk ikke kjørt docker-compose uten å endre denne til  `./tiltakspenger/tiltakspenger-vedtak`, siden dette er mappestrukturen man har by default i metarepoet etter man henter ned tp-repoene. Bør denne endres, eller er det bare mitt oppsett som er feil?

2023-12-08 15:42 UTC, richardmartinsen commented on docker-compose.yml
> +      context: ./tiltakspenger-vedtak
Snodig. Det må vi sjekke ut...
Jeg hadde trodde at enten ../tiltakspenger/tiltakspenger-vedtak eller ./tiltakspenger-vedtak skulle virke, men kanskje det er jeg som har feil oppsett.

2023-12-11 14:49 UTC, benedihm commented on docker-compose.yml
> +      context: ./tiltakspenger-vedtak
Problemet lå hos meg som har clonet repoet feil! Så da bør alt være ok slik som det er! 😄

2023-12-11 14:50 UTC, benedihm approved these changes

2023-12-12 11:33 UTC, merged